# MangoHud config for Compute-v1 CARLA profiling
#
# Lives in: brazel_diagnostics/perf/

no_display
log_interval=100
log_duration=0
output_folder=/mnt/av-storage/brazel_ws/src/brazel_diagnostics/perf/profiles
fps
frametime
